name: build
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Set up Go
            uses: actions/setup-go@v4
            with:
              go-version-file: 'go.mod'
              cache-dependency-path: subdir/go.sum
          - name: Install Protoc
            uses: arduino/setup-protoc@v2
            with:
                repo-token: ${{ secrets.GITHUB_TOKEN }}
          - name: Build
            run: make
          - name: Test
            run: make test