name: build
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Set up Go
            uses: actions/setup-go@v5
            with:
              go-version-file: 'go.mod'
              cache-dependency-path: subdir/go.sum
          - name: Install Protoc
            uses: arduino/setup-protoc@v3
            with:
                repo-token: ${{ secrets.GITHUB_TOKEN }}
          - name: Protogen
            run: protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative $(find . -type f -name '*.proto')
          - name: Installing protoc-gen-go
            run: |
              go get github.com/golang/protobuf/protoc-gen-go
              go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
          - name: Build
            run: go build -v ./...
          - name: Test
            run: go test -v ./...